'use client';
import { motion } from 'framer-motion';

export const MotionNav = motion.nav;
export const MotionFooter = motion.footer;
export const MotionHeader = motion.header;
export const MotionDiv = motion.div;
export const MotionSection = motion.section;
export const MotionMain = motion.main;
export const MotionSpan = motion.span;
export const MotionUl = motion.ul;
export const MotionLi = motion.li;
export const MotionButton = motion.button;
export const MotionH1 = motion.h1;
export const MotionH2 = motion.h2;
export const MotionH3 = motion.h3;
export const MotionH4 = motion.h4;
export const MotionH5 = motion.h5;
export const MotionH6 = motion.h6;
export const MotionP = motion.p;
